[build]
  command = "bash netlify_build.sh"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "stable"

# Cache the Flutter SDK
[[plugins]]
  package = "@netlify/plugin-cache"
  
[context.production]
  plugins = ["@netlify/plugin-cache"]