name: portfolio_web_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & State Management
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_fonts: ^8.0.2
  
  # Images & Media
  cached_network_image: ^3.4.1
  visibility_detector: ^0.4.0+2
  video_player: ^2.11.1
  
  # Networking & Forms
  http: ^1.6.0
  fluttertoast: ^9.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  # Assets section for images only
  assets:
    # Root asset folders
    - assets/images/

    # UI Design Assets
    - assets/images/ui/cao_cao_investment/
    - assets/images/ui/portfolio_website/
    - assets/images/ui/prayer_box/

    # Graphic Design Assets - Poster Type Structure
    - assets/images/graphic/posters/social_media/
    - assets/images/graphic/posters/print_materials/

    - assets/images/graphic/banners/
    - assets/images/graphic/logos/

    # OuKrag Logo Video
    - assets/images/graphic/logos/OuKrag_Logo_Video.mp4
